### ISSUE TITLE
Question: Why do you have to use HashRouter?

### ISSUE THREAD

**Issue by ndtreviv** [nateshmbhat/electron-react-ts-starter#3]
As per title. Is it a limitation of using React in electron, or is it a limitation of this setup?

**Comment by sns-sem** [comment]
It's a limitation of using react in electron. While you don't have to use HashRouter in development, it is required in production. Without it, it will change the path of off your index file, which does not exist on the local machine and will cause an error.

It works in development because it's using a development server which is serving the files instead of serving the static html file.
